---
language: java
jdk: openjdk11
dist: xenial

git:
  depth: false
  quiet: true

cache:
  directories:
    - ${HOME}/.m2/repository
    - ${HOME}/artifacts

# branches:
#   only:
#     - - /^OPSEXP-.*$/

stages:
  - build and test
  - release

jobs:
  include:
    - stage: build and test
      name: "Build and Test"
      script:
        - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        - sysctl net.ipv4.ip_forward=1
        - mvn clean install