---
dist: xenial
sudo: required
language: java
jdk:
  - openjdk11

# the cache can grow constantly
before_cache:
  - rm -rf $HOME/.m2/repository/org/alfresco/alfresco-lambda-java-utils

cache:
  directories:
    - ${HOME}/.m2
    - ${HOME}/.m2/repository

git:
  depth: false
  quiet: true

stages:
  - build
  - release

jobs:
  include:
    - name: "Build and Test"
      stage: build
      script:
        - mvn clean install
    - name: "Push to  Nexus"
      stage: release
      before_script:
      if: branch = master AND commit_message =~ /\[release\]/
      before_install:
        - "cp .travis.settings.xml $HOME/.m2/settings.xml"
      script:
        - mvn -B -V deploy